//! MCP server core — struct definition, `ServerHandler` implementation,
//! and `serve()` entry point for stdio transport.

use std::sync::Arc;

use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::ServerHandler;
use rmcp::model::{
    GetPromptRequestParams, GetPromptResult, Implementation, ListPromptsResult,
    ListResourceTemplatesResult, ListResourcesResult, PaginatedRequestParams,
    ReadResourceRequestParams, ReadResourceResult, ServerCapabilities, ServerInfo,
};
use rmcp::service::{RequestContext, RoleServer};
use rmcp::tool_handler;
use rmcp::transport::io::stdio;
use rmcp::ServiceExt;
use sqlx::PgPool;

use crate::config::AppConfig;
use crate::engine::error::ScorchError;

/// The `ScorchKit` MCP server.
///
/// Holds shared application state (configuration and database pool)
/// that all MCP tool methods can access. The `tool_router` field is
/// generated by the `#[tool_router]` macro on the tools impl block.
pub struct ScorchKitServer {
    /// Shared application configuration.
    pub(crate) config: Arc<AppConfig>,
    /// `PostgreSQL` connection pool for storage operations.
    pub(crate) pool: PgPool,
    /// Generated tool router for MCP tool dispatch.
    tool_router: ToolRouter<Self>,
}

impl ScorchKitServer {
    /// Create a new server instance with the given config and database pool.
    #[must_use]
    pub fn new(config: Arc<AppConfig>, pool: PgPool) -> Self {
        Self { config, pool, tool_router: Self::tool_router() }
    }
}

#[tool_handler]
impl ServerHandler for ScorchKitServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .enable_prompts()
                .build(),
        )
        .with_server_info(Implementation::new("scorchkit", env!("CARGO_PKG_VERSION")))
        .with_instructions(super::instructions::INSTRUCTIONS.to_string())
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, rmcp::ErrorData> {
        self.do_list_resources().await
    }

    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, rmcp::ErrorData> {
        Ok(self.do_list_resource_templates())
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, rmcp::ErrorData> {
        self.do_read_resource(&request.uri).await
    }

    async fn list_prompts(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListPromptsResult, rmcp::ErrorData> {
        Ok(ListPromptsResult { prompts: Self::do_list_prompts(), meta: None, next_cursor: None })
    }

    async fn get_prompt(
        &self,
        request: GetPromptRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<GetPromptResult, rmcp::ErrorData> {
        let arguments = request
            .arguments
            .unwrap_or_default()
            .into_iter()
            .map(|(k, v)| {
                let s = v.as_str().map_or_else(|| v.to_string(), str::to_string);
                (k, s)
            })
            .collect();

        Self::do_get_prompt(&request.name, &arguments)
            .map_err(|e| rmcp::ErrorData::invalid_params(e, None::<serde_json::Value>))
    }
}

/// Start the MCP server on stdio transport.
///
/// Connects to the database, creates the server, and runs indefinitely
/// handling MCP requests over stdin/stdout.
///
/// # Errors
///
/// Returns an error if the database connection fails or the MCP transport
/// encounters an I/O error.
pub async fn serve(config: Arc<AppConfig>) -> crate::engine::error::Result<()> {
    let pool = crate::storage::connect_from_config(&config.database, None).await?;

    let server = ScorchKitServer::new(config, pool);

    let service = server
        .serve(stdio())
        .await
        .map_err(|e| ScorchError::Config(format!("MCP server failed to start: {e}")))?;

    service.waiting().await.map_err(|e| ScorchError::Config(format!("MCP server error: {e}")))?;

    Ok(())
}
